# Pandas DataFrames: Writing Pandorable Code

In [21]:
import pandas as pd

census = pd.read_excel('Data\census.xlsx')
census.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

## #1 Avoid Chain Indexing ']['

df.loc['Wastenaw']['Total Polulation'] This will pull the rows with the index 'Washtenaw' and only the 'Total Pollution' Column If you see a ][ you should think carefully about what you are doing.

- loc is label-based. This means that if you write loc[2], you are looking for the values of your DataFrame that have an index labeled 2.
- iloc is position-based. This means that if you write iloc[2], you are looking for the values of your DataFrame that are at index 2.

In [10]:
#Remember, a dataframe is a a stack of series.
#The code below pulls the first row based on it's index
census.iloc[0].head()

SUMLEV      40
REGION       3
DIVISION     6
STATE        1
COUNTY       0
Name: 0, dtype: object

In [22]:
#The code below pulls the first row based on it's label
census.set_index(['STNAME','CTYNAME'], inplace = True)
census.loc[('Alabama','Autauga County')]

C:\Users\iwatanabe\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: PerformanceWarning: indexing past lexsort depth may impact performance.
  This is separate from the ipykernel package so we can avoid doing imports until

,,SUMLEV,REGION,DIVISION,STATE,COUNTY,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,CTYNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,Autauga County,50,3,6,1,1,54571,54571,54660,55253,55175,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.59227,-2.187333

In [28]:
#The following code pulls the DIVISON and CENSUS2010POP for Autauga County in Alabama
#Note the structure [Row Label, Column Label]
# .loc[ROW LABEL, COLUMN INDEX] will not work (e.g. census.loc[('Alabama','Autauga County'),[1:4] )
census.loc[('Alabama','Autauga County'),['DIVISION','CENSUS2010POP']]

C:\Users\iwatanabe\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:1472: PerformanceWarning: indexing past lexsort depth may impact performance.
  return self._getitem_tuple(key)

                        DIVISION  CENSUS2010POP
STNAME  CTYNAME
Alabama Autauga County         6          54571

In [29]:

census.iloc[0,1:4]

REGION      3.0
DIVISION    6.0
STATE       1.0
Name: (Alabama, Alabama), dtype: float64

## #2 Chain your Methods using 1) Parentheses, and 2) New Lines

In python if you begin with an open parenthesis you can span a statement over multiple lines

In [11]:
(
    census.where(census['SUMLEV'] == 50)
        .dropna()
        .set_index(['STNAME','CTYNAME'])
        .rename(columns={'ESTIMATESBASE2010':'Estimates Base 2010'})
        .head()
)

                        SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County    50.0     3.0       6.0    1.0     1.0
        Baldwin County    50.0     3.0       6.0    1.0     3.0
        Barbour County    50.0     3.0       6.0    1.0     5.0
        Bibb County       50.0     3.0       6.0    1.0     7.0
        Blount County     50.0     3.0       6.0    1.0     9.0

                        CENSUS2010POP  Estimates Base 2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County        54571.0              54571.0          54660.0
        Baldwin County       182265.0             182265.0         183193.0
        Barbour County        27457.0              27457.0          27341.0
        Bibb County           22915.0              22919.0          22861.0
        Blount County         57322.0              57322.0          57373.0

                        POPESTIMATE2011  POPESTIMATE2012     ...       \
STNAME  CTYNAME                                              ...
Alabama Autauga County          55253.0          55175.0     ...
        Baldwin County         186659.0         190396.0     ...
        Barbour County          27226.0          27159.0     ...
        Bibb County             22733.0          22642.0     ...
        Blount County           57711.0          57776.0     ...

                        RDOMESTICMIG2011  RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME  CTYNAME
Alabama Autauga County          7.242091         -2.915927         -3.012349
        Baldwin County         14.832960         17.647293         21.845705
        Barbour County         -4.728132         -2.500690         -7.056824
        Bibb County            -5.527043         -5.068871         -6.201001
        Blount County           1.807375         -1.177622         -1.748766

                        RDOMESTICMIG2014  RDOMESTICMIG2015  RNETMIG2011  \
STNAME  CTYNAME
Alabama Autauga County          2.265971         -2.530799     7.606016
        Baldwin County         19.243287         17.197872    15.844176
        Barbour County         -3.904217        -10.543299    -4.874741
        Bibb County            -0.177537          0.177258    -5.088389
        Blount County          -2.062535         -1.369970     1.859511

                        RNETMIG2012  RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County    -2.626146    -2.722002     2.592270    -2.187333
        Baldwin County    18.559627    22.727626    20.317142    18.293499
        Barbour County    -2.758113    -7.167664    -3.978583   -10.543299
        Bibb County       -4.363636    -5.403729     0.754533     1.107861
        Blount County     -0.848580    -1.402476    -1.577232    -0.884411

[5 rows x 98 columns]

## #3 Apply Functions to Rows in a DataFrame Using apply()

In [30]:
# Say we want to get the minimum and maximum values for the population estimate across the years

import numpy as np

# Quick note: How to pull multiple columns from a DataFrame
# THIS WILL FAIL: census['POPESTIMATE2010','POPESTIMATE2011']
# You must wrap the multiple column names in a list
census[['POPESTIMATE2010','POPESTIMATE2011']].head()

                        POPESTIMATE2010  POPESTIMATE2011
STNAME  CTYNAME
Alabama Alabama                 4785161          4801108
        Autauga County            54660            55253
        Baldwin County           183193           186659
        Barbour County            27341            27226
        Bibb County               22861            22733

In [31]:
def min_max(row):
    data = row[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
    return pd.Series({'min':np.min(data), 'max':np.max(data)})

aa = census.apply(min_max, axis=1).head() #Takes the series 
#returned for each row, flips them 90 degrees clockwise and stacks them
aa.head()

                              min        max
STNAME  CTYNAME
Alabama Alabama         4785161.0  4858979.0
        Autauga County    54660.0    55347.0
        Baldwin County   183193.0   203709.0
        Barbour County    26489.0    27341.0
        Bibb County       22512.0    22861.0

In [32]:
# As you would expect, we can use lamba function in the apply method
rows = ['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']

census.apply(lambda x: np.max(x[rows]), axis=1).head()

STNAME   CTYNAME
Alabama  Alabama           4858979.0
         Autauga County      55347.0
         Baldwin County     203709.0
         Barbour County      27341.0
         Bibb County         22861.0
dtype: float64